# Generated by Django 3.2.9 on 2021-12-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_sorts_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorts',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
